name: Node CI

# 指定触发action的事件
on:
  push:
    # 指定触发指定事件的分支 仅master触发
    branches:
      - master
  pull_request: # 待测试
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ strategy.matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ strategy.matrix.node-version }}
      - name: 执行npm install
        run: |
          npm install
        env:
          CI: true

      - name: 部署h5示例应用
        run: |
          cd packages/demo
          npm install
          npm run build:h5
          cd dist
          git init
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git remote set-url origin https://lexmin0412:${{ secrets.USER_PWD }}@github.com/lexmin0412/taro-xui-h5-sample.git
          git add .
          git commit -m 'deploy'
          git push -f origin HEAD:master
      - name: 发送企业微信推送消息
        run: |
          node qywxrobot.js key=${{secrets.QYWX_ROBOT_KEY}}